//go:build ignore

// Generate embedded notices from the packages linked into both release targets.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strconv"
	"strings"
)

var noticeName = regexp.MustCompile(`(?i)^(licen[cs]e|copying|notice|copyright(?:notice)?|patents)([._-].*)?$`)

type module struct {
	Path, Version, Dir string
	Replace            *module
}

type pkg struct {
	Dir      string
	Standard bool
	Module   *module
}

func run(args ...string) []byte {
	cmd := exec.Command("go", args...)
	cmd.Stderr = os.Stderr
	output, err := cmd.Output()
	if err != nil {
		panic(err)
	}
	return output
}

func main() {
	agentRoot := filepath.Dir(strings.TrimSpace(string(run("env", "GOMOD"))))
	goroot := strings.TrimSpace(string(run("env", "GOROOT")))
	notices := map[string]string{}
	seen := map[string]bool{}
	add := func(path, label string) {
		if seen[path] {
			return
		}
		text, err := os.ReadFile(path)
		if err != nil {
			panic(err)
		}
		if len(bytes.TrimSpace(text)) == 0 {
			panic("empty license notice: " + path)
		}
		seen[path] = true
		notices[label] = string(text)
	}
	add(filepath.Join(agentRoot, "..", "LICENSE"), "HLG")
	add(filepath.Join(goroot, "LICENSE"), "Go runtime and standard library ("+runtime.Version()+") / LICENSE")
	if path := filepath.Join(goroot, "PATENTS"); fileExists(path) {
		add(path, "Go runtime and standard library ("+runtime.Version()+") / PATENTS")
	}

	// Also preserve notices in package-specific and Go-vendored directories;
	// those may have copyrights distinct from the top-level Go license.
	scan := func(dir, root, label string) bool {
		found := false
		for {
			entries, err := os.ReadDir(dir)
			if err != nil {
				panic(err)
			}
			for _, entry := range entries {
				if entry.IsDir() || !noticeName.MatchString(entry.Name()) {
					continue
				}
				path := filepath.Join(dir, entry.Name())
				rel, _ := filepath.Rel(root, path)
				add(path, label+" / "+filepath.ToSlash(rel))
				if strings.HasPrefix(strings.ToLower(entry.Name()), "licen") || strings.HasPrefix(strings.ToLower(entry.Name()), "copying") {
					found = true
				}
			}
			if dir == root {
				return found
			}
			parent := filepath.Dir(dir)
			if parent == dir {
				panic("license directory escaped its root: " + root)
			}
			dir = parent
		}
	}
	for _, arch := range []string{"amd64", "arm64"} {
		cmd := exec.Command("go", "list", "-deps", "-json", "./cmd/hlg-agent")
		cmd.Dir = agentRoot
		cmd.Env = append(os.Environ(), "CGO_ENABLED=0", "GOOS=linux", "GOARCH="+arch)
		cmd.Stderr = os.Stderr
		output, err := cmd.Output()
		if err != nil {
			panic(err)
		}
		decoder := json.NewDecoder(bytes.NewReader(output))
		for {
			var p pkg
			if err := decoder.Decode(&p); err == io.EOF {
				break
			} else if err != nil {
				panic(err)
			}
			if p.Dir == "" { // Compiler pseudo-packages, such as unsafe.
				continue
			}
			if p.Standard {
				scan(p.Dir, filepath.Join(goroot, "src"), "Go runtime package notices")
			} else if m := p.Module; m != nil {
				if m.Replace != nil {
					m = m.Replace
				}
				if m.Dir == agentRoot {
					continue
				}
				if !scan(p.Dir, m.Dir, m.Path+"@"+m.Version) {
					panic("no license text found for linked module: " + m.Path)
				}
			} else {
				panic("cannot identify license owner of linked package: " + p.Dir)
			}
		}
	}
	keys := make([]string, 0, len(notices))
	for key := range notices {
		if key != "HLG" {
			keys = append(keys, key)
		}
	}
	sort.Strings(keys)
	keys = append([]string{"HLG"}, keys...)
	var text strings.Builder
	text.WriteString("Homura Looking Glass Agent — license notices\n\n")
	for _, key := range keys {
		fmt.Fprintf(&text, "=== %s ===\n\n%s\n\n", key, strings.TrimRight(notices[key], "\n"))
	}
	source := "// Code generated by go generate; DO NOT EDIT.\n\npackage licenses\n\nfunc init() { text = " + strconv.Quote(text.String()) + " }\n"
	formatted, err := format.Source([]byte(source))
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(filepath.Join(agentRoot, "internal", "licenses", "notices_generated.go"), formatted, 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("embedded %d license/notice texts for linux/amd64 and linux/arm64\n", len(notices))
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}
